apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: myapp-replica
  namespace: test
  labels:
    app: myapp
    tier: frontend
spec:
  replicas: 3
  selector:
    matchLabels:
      tier: frontend
  template:
    metadata:
      name: myapp
      labels:
       env: dev
       tier: frontend
    spec:
      containers:
        - name: nginx-controller
          image: nginx
